### ISSUE TITLE
Textarea does not accept field attribute

### ISSUE THREAD

**Issue by bluejack** [bluzky/salad_ui#48]
The documentation sort of implies it does. But if it doesn't, how do we bind it to a form?

**Comment by bluzky** [comment]
Thanks for reporting, I'm working to fix this issue.
I'm building a form demo and testing all form input.

**Comment by bluzky** [comment]
Hi @bluejack, I have fixed this in PR #49

**Comment by roylez** [comment]
No this is not fixed. I do not see it in the list of changed files for #49
